/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// EXTERNAL INCLUDES

// INTERNAL INCLUDES
#include <dali-csharp-binder/common/common.h>

#include <dali/dali.h>

#include <dali/integration-api/debug.h>

using namespace Dali;

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_0()
{
  void*                  jresult;
  Dali::Property::Value* result = 0;

  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value();
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_1(bool jarg1)
{
  void*                  jresult;
  bool                   arg1;
  Dali::Property::Value* result = 0;

  arg1 = jarg1 ? true : false;
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value(arg1);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_2(int jarg1)
{
  void*                  jresult;
  int                    arg1;
  Dali::Property::Value* result = 0;

  arg1 = (int)jarg1;
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value(arg1);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_3(float jarg1)
{
  void*                  jresult;
  float                  arg1;
  Dali::Property::Value* result = 0;

  arg1 = (float)jarg1;
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value(arg1);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_4(void* jarg1)
{
  void*                  jresult;
  Dali::Vector2*         arg1   = 0;
  Dali::Property::Value* result = 0;

  arg1 = (Dali::Vector2*)jarg1;
  if(!arg1)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Vector2 const & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value((Dali::Vector2 const&)*arg1);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_5(void* jarg1)
{
  void*                  jresult;
  Dali::Vector3*         arg1   = 0;
  Dali::Property::Value* result = 0;

  arg1 = (Dali::Vector3*)jarg1;
  if(!arg1)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Vector3 const & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value((Dali::Vector3 const&)*arg1);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_6(void* jarg1)
{
  void*                  jresult;
  Dali::Vector4*         arg1   = 0;
  Dali::Property::Value* result = 0;

  arg1 = (Dali::Vector4*)jarg1;
  if(!arg1)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Vector4 const & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value((Dali::Vector4 const&)*arg1);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_7(void* jarg1)
{
  void*                  jresult;
  Dali::Matrix3*         arg1   = 0;
  Dali::Property::Value* result = 0;

  arg1 = (Dali::Matrix3*)jarg1;
  if(!arg1)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Matrix3 const & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value((Dali::Matrix3 const&)*arg1);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_8(void* jarg1)
{
  void*                  jresult;
  Dali::Matrix*          arg1   = 0;
  Dali::Property::Value* result = 0;

  arg1 = (Dali::Matrix*)jarg1;
  if(!arg1)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Matrix const & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value((Dali::Matrix const&)*arg1);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_9(void* jarg1)
{
  void*                  jresult;
  Dali::Rect<int>*       arg1   = 0;
  Dali::Property::Value* result = 0;

  arg1 = (Dali::Rect<int>*)jarg1;
  if(!arg1)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Rect< int > const & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value((Dali::Rect<int> const&)*arg1);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_10(void* jarg1)
{
  void*                  jresult;
  Dali::AngleAxis*       arg1   = 0;
  Dali::Property::Value* result = 0;

  arg1 = (Dali::AngleAxis*)jarg1;
  if(!arg1)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::AngleAxis const & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value((Dali::AngleAxis const&)*arg1);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_11(void* jarg1)
{
  void*                  jresult;
  Dali::Quaternion*      arg1   = 0;
  Dali::Property::Value* result = 0;

  arg1 = (Dali::Quaternion*)jarg1;
  if(!arg1)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Quaternion const & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value((Dali::Quaternion const&)*arg1);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_12(char* jarg1)
{
  void*                  jresult;
  Dali::String*          arg1   = 0;
  Dali::Property::Value* result = 0;

  if(!jarg1)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  Dali::String arg1_str(jarg1);
  arg1 = &arg1_str;
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value((Dali::String const&)*arg1);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;

  //argout typemap for const Dali::String&

  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_14(void* jarg1)
{
  void*                  jresult;
  Dali::Property::Array* arg1   = 0;
  Dali::Property::Value* result = 0;

  arg1 = (Dali::Property::Array*)jarg1;
  if(!arg1)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Property::Array & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value(*arg1);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_15(void* jarg1)
{
  void*                  jresult;
  Dali::Property::Map*   arg1   = 0;
  Dali::Property::Value* result = 0;

  arg1 = (Dali::Property::Map*)jarg1;
  if(!arg1)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Property::Map & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value(*arg1);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_16(void* jarg1)
{
  void*                  jresult;
  Extents*               arg1   = 0;
  Dali::Property::Value* result = 0;

  arg1 = (Extents*)jarg1;
  if(!arg1)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Extents const & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value((Extents const&)*arg1);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_17(int jarg1)
{
  void*                  jresult;
  Dali::Property::Type   arg1;
  Dali::Property::Value* result = 0;

  arg1 = (Dali::Property::Type)jarg1;
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value(arg1);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value__SWIG_18(void* jarg1)
{
  void*                  jresult;
  Dali::Property::Value* arg1   = 0;
  Dali::Property::Value* result = 0;

  arg1 = (Dali::Property::Value*)jarg1;
  if(!arg1)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Property::Value const & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value((Dali::Property::Value const&)*arg1);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_EqualTo(void* jarg1, void* jarg2)
{
  bool                   jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Property::Value* arg2 = 0;
  bool                   result;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Property::Value*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Property::Value const & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (bool)((Dali::Property::Value const*)arg1)->operator==((Dali::Property::Value const&)*arg2);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = result;
  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_NotEqualTo(void* jarg1, void* jarg2)
{
  bool                   jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Property::Value* arg2 = 0;
  bool                   result;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Property::Value*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Property::Value const & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (bool)((Dali::Property::Value const*)arg1)->operator!=((Dali::Property::Value const&)*arg2);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = result;
  return jresult;
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_delete_Property_Value(void* jarg1)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;

  arg1 = (Dali::Property::Value*)jarg1;
  {
    try
    {
      delete arg1;
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT int SWIGSTDCALL CSharp_Dali_Property_Value_GetType(void* jarg1)
{
  int                    jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Property::Type   result;

  arg1 = (Dali::Property::Value*)jarg1;
  {
    try
    {
      result = (Dali::Property::Type)((Dali::Property::Value const*)arg1)->GetType();
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (int)result;
  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get__SWIG_1(void* jarg1, bool* jarg2)
{
  bool                   jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  bool*                  arg2 = 0;
  bool                   result;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (bool*)jarg2;
  {
    try
    {
      result = (bool)((Dali::Property::Value const*)arg1)->Get(*arg2);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = result;
  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get__SWIG_2(void* jarg1, float* jarg2)
{
  bool                   jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  float*                 arg2 = 0;
  bool                   result;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (float*)jarg2;
  {
    try
    {
      result = (bool)((Dali::Property::Value const*)arg1)->Get(*arg2);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = result;
  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get__SWIG_3(void* jarg1, int* jarg2)
{
  bool                   jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  int*                   arg2 = 0;
  bool                   result;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (int*)jarg2;
  {
    try
    {
      result = (bool)((Dali::Property::Value const*)arg1)->Get(*arg2);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = result;
  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get__SWIG_4(void* jarg1, void* jarg2)
{
  bool                   jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Rect<int>*       arg2 = 0;
  bool                   result;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Rect<int>*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Rect< int > & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (bool)((Dali::Property::Value const*)arg1)->Get(*arg2);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = result;
  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get__SWIG_5(void* jarg1, void* jarg2)
{
  bool                   jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Vector2*         arg2 = 0;
  bool                   result;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Vector2*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Vector2 & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (bool)((Dali::Property::Value const*)arg1)->Get(*arg2);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = result;
  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get__SWIG_6(void* jarg1, void* jarg2)
{
  bool                   jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Vector3*         arg2 = 0;
  bool                   result;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Vector3*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Vector3 & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (bool)((Dali::Property::Value const*)arg1)->Get(*arg2);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = result;
  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get__SWIG_7(void* jarg1, void* jarg2)
{
  bool                   jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Vector4*         arg2 = 0;
  bool                   result;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Vector4*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Vector4 & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (bool)((Dali::Property::Value const*)arg1)->Get(*arg2);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = result;
  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get__SWIG_8(void* jarg1, void* jarg2)
{
  bool                   jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Matrix3*         arg2 = 0;
  bool                   result;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Matrix3*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Matrix3 & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (bool)((Dali::Property::Value const*)arg1)->Get(*arg2);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = result;
  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get__SWIG_9(void* jarg1, void* jarg2)
{
  bool                   jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Matrix*          arg2 = 0;
  bool                   result;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Matrix*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Matrix & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (bool)((Dali::Property::Value const*)arg1)->Get(*arg2);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = result;
  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get__SWIG_10(void* jarg1, void* jarg2)
{
  bool                   jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::AngleAxis*       arg2 = 0;
  bool                   result;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::AngleAxis*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::AngleAxis & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (bool)((Dali::Property::Value const*)arg1)->Get(*arg2);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = result;
  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get__SWIG_11(void* jarg1, void* jarg2)
{
  bool                   jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Quaternion*      arg2 = 0;
  bool                   result;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Quaternion*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Quaternion & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (bool)((Dali::Property::Value const*)arg1)->Get(*arg2);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = result;
  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get__SWIG_12(void* jarg1, char** jarg2)
{
  bool                   jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  bool                   result;

  arg1 = (Dali::Property::Value*)jarg1;

  //typemap in
  Dali::String temp;
  {
    try
    {
      result = (bool)((Dali::Property::Value const*)arg1)->Get(temp);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = result;

  //Typemap argout in c++ file.
  //This will convert c++ string to c# string
  *jarg2 = SWIG_csharp_string_callback(temp.CStr());

  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get__SWIG_13(void* jarg1, void* jarg2)
{
  bool                   jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Property::Array* arg2 = 0;
  bool                   result;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Property::Array*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Property::Array & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (bool)((Dali::Property::Value const*)arg1)->Get(*arg2);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = result;
  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get__SWIG_14(void* jarg1, void* jarg2)
{
  bool                   jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Property::Map*   arg2 = 0;
  bool                   result;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Property::Map*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Property::Map & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (bool)((Dali::Property::Value const*)arg1)->Get(*arg2);
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = result;
  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get__SWIG_15(void* jarg1, void* jarg2)
{
  bool                   jresult;
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Extents*               arg2 = 0;
  bool                   result;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Extents*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Extents & type is null", 0);
    return 0;
  }
  {
    try
    {
      result = (bool)((Dali::Property::Value const*)arg1)->Get(*arg2);
    }
    CALL_CATCH_EXCEPTION(0);
  }
  jresult = result;
  return jresult;
}

// For internal managed memory optimization
SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value_Vector2_Componentwise(float x, float y)
{
  void*                  jresult;
  Dali::Property::Value* result = 0;
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value(Dali::Vector2(x, y));
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value_Vector3_Componentwise(float x, float y, float z)
{
  void*                  jresult;
  Dali::Property::Value* result = 0;
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value(Dali::Vector3(x, y, z));
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT void* SWIGSTDCALL CSharp_Dali_new_Property_Value_Vector4_Componentwise(float x, float y, float z, float w)
{
  void*                  jresult;
  Dali::Property::Value* result = 0;
  {
    try
    {
      result = (Dali::Property::Value*)new Dali::Property::Value(Dali::Vector4(x, y, z, w));
    }
    CALL_CATCH_EXCEPTION(0);
  }

  jresult = (void*)result;
  return jresult;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get_Vector2_Componentwise(void* csPropertyValue, float* outX, float* outY)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  bool                   result;

  arg1 = (Dali::Property::Value*)csPropertyValue;
  {
    try
    {
      Dali::Vector2 value;
      result = (bool)((Dali::Property::Value const*)arg1)->Get(value);
      if(result)
      {
        *outX = value.x;
        *outY = value.y;
      }
    }
    CALL_CATCH_EXCEPTION(0);
  }

  return result;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get_Vector3_Componentwise(void* csPropertyValue, float* outX, float* outY, float* outZ)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  bool                   result;

  arg1 = (Dali::Property::Value*)csPropertyValue;
  {
    try
    {
      Dali::Vector3 value;
      result = (bool)((Dali::Property::Value const*)arg1)->Get(value);
      if(result)
      {
        *outX = value.x;
        *outY = value.y;
        *outZ = value.z;
      }
    }
    CALL_CATCH_EXCEPTION(0);
  }

  return result;
}

SWIGEXPORT bool SWIGSTDCALL CSharp_Dali_Property_Value_Get_Vector4_Componentwise(void* csPropertyValue, float* outX, float* outY, float* outZ, float* outW)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  bool                   result;

  arg1 = (Dali::Property::Value*)csPropertyValue;
  {
    try
    {
      Dali::Vector4 value;
      result = (bool)((Dali::Property::Value const*)arg1)->Get(value);
      if(result)
      {
        *outX = value.x;
        *outY = value.y;
        *outZ = value.z;
        *outW = value.w;
      }
    }
    CALL_CATCH_EXCEPTION(0);
  }

  return result;
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set__SWIG_1(void* jarg1, bool jarg2)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  bool                   arg2;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = jarg2 ? true : false;
  {
    try
    {
      *((Dali::Property::Value*)arg1) = arg2;
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set__SWIG_2(void* jarg1, float jarg2)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  float                  arg2;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (float)jarg2;
  {
    try
    {
      *((Dali::Property::Value*)arg1) = arg2;
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set__SWIG_3(void* jarg1, int jarg2)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  int                    arg2;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (int)jarg2;
  {
    try
    {
      *((Dali::Property::Value*)arg1) = arg2;
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set__SWIG_5(void* jarg1, void* jarg2)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Vector2*         arg2 = 0;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Vector2*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Vector2 const & type is null", 0);
    return;
  }
  {
    try
    {
      *((Dali::Property::Value*)arg1) = (Dali::Vector2 const&)*arg2;
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set__SWIG_6(void* jarg1, void* jarg2)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Vector3*         arg2 = 0;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Vector3*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Vector3 const & type is null", 0);
    return;
  }
  {
    try
    {
      *((Dali::Property::Value*)arg1) = (Dali::Vector3 const&)*arg2;
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set__SWIG_7(void* jarg1, void* jarg2)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Vector4*         arg2 = 0;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Vector4*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Vector4 const & type is null", 0);
    return;
  }
  {
    try
    {
      *((Dali::Property::Value*)arg1) = (Dali::Vector4 const&)*arg2;
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set__SWIG_8(void* jarg1, void* jarg2)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Matrix3*         arg2 = 0;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Matrix3*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Matrix3 const & type is null", 0);
    return;
  }
  {
    try
    {
      *((Dali::Property::Value*)arg1) = (Dali::Matrix3 const&)*arg2;
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set__SWIG_9(void* jarg1, void* jarg2)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Matrix*          arg2 = 0;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Matrix*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Matrix const & type is null", 0);
    return;
  }
  {
    try
    {
      *((Dali::Property::Value*)arg1) = (Dali::Matrix const&)*arg2;
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set__SWIG_10(void* jarg1, void* jarg2)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Rect<int>*       arg2 = 0;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Rect<int>*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Rect< int > const & type is null", 0);
    return;
  }
  {
    try
    {
      *((Dali::Property::Value*)arg1) = (Dali::Rect<int> const&)*arg2;
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set__SWIG_11(void* jarg1, void* jarg2)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::AngleAxis*       arg2 = 0;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::AngleAxis*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::AngleAxis const & type is null", 0);
    return;
  }
  {
    try
    {
      *((Dali::Property::Value*)arg1) = (Dali::AngleAxis const&)*arg2;
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set__SWIG_12(void* jarg1, void* jarg2)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Quaternion*      arg2 = 0;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Quaternion*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Quaternion const & type is null", 0);
    return;
  }
  {
    try
    {
      *((Dali::Property::Value*)arg1) = (Dali::Quaternion const&)*arg2;
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set__SWIG_13(void* jarg1, char* jarg2)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::String*          arg2 = 0;

  arg1 = (Dali::Property::Value*)jarg1;
  if(!jarg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return;
  }
  Dali::String arg2_str(jarg2);
  arg2 = &arg2_str;
  {
    try
    {
      *((Dali::Property::Value*)arg1) = (Dali::String const&)*arg2;
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set__SWIG_14(void* jarg1, void* jarg2)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Property::Array* arg2 = 0;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Property::Array*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Property::Array & type is null", 0);
    return;
  }
  {
    try
    {
      *((Dali::Property::Value*)arg1) = *arg2;
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set__SWIG_15(void* jarg1, void* jarg2)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Dali::Property::Map*   arg2 = 0;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Dali::Property::Map*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Dali::Property::Map & type is null", 0);
    return;
  }
  {
    try
    {
      *((Dali::Property::Value*)arg1) = *arg2;
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set__SWIG_16(void* jarg1, void* jarg2)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;
  Extents*               arg2 = 0;

  arg1 = (Dali::Property::Value*)jarg1;
  arg2 = (Extents*)jarg2;
  if(!arg2)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Extents const & type is null", 0);
    return;
  }
  {
    try
    {
      *((Dali::Property::Value*)arg1) = (Extents const&)*arg2;
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set_Vector2_Componentwise(void* jarg1, float x, float y)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;

  arg1 = (Dali::Property::Value*)jarg1;
  {
    try
    {
      *((Dali::Property::Value*)arg1) = Dali::Vector2(x, y);
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set_Vector3_Componentwise(void* jarg1, float x, float y, float z)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;

  arg1 = (Dali::Property::Value*)jarg1;
  {
    try
    {
      *((Dali::Property::Value*)arg1) = Dali::Vector3(x, y, z);
    }
    CALL_CATCH_EXCEPTION();
  }
}

SWIGEXPORT void SWIGSTDCALL CSharp_Dali_Property_Value_Set_Vector4_Componentwise(void* jarg1, float x, float y, float z, float w)
{
  Dali::Property::Value* arg1 = (Dali::Property::Value*)0;

  arg1 = (Dali::Property::Value*)jarg1;
  {
    try
    {
      *((Dali::Property::Value*)arg1) = Dali::Vector4(x, y, z, w);
    }
    CALL_CATCH_EXCEPTION();
  }
}

#ifdef __cplusplus
}
#endif
