/** Copyright (c) 2017 Samsung Electronics Co., Ltd.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*
*/
// This File has been auto-generated by SWIG and then modified using DALi Ruby Scripts
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.9
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Dali {

public partial class ImageView : View {

  public override void Dispose() {
    if (!Stage.IsInstalled()) {
      DisposeQueue.Instance.Add(this);
      return;
    }

    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NDalicPINVOKE.delete_ImageView(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }




  public ImageView () : this (NDalicPINVOKE.ImageView_New__SWIG_0(), true) {
      if (NDalicPINVOKE.SWIGPendingException.Pending) throw NDalicPINVOKE.SWIGPendingException.Retrieve();

  }
  public ImageView (string url) : this (NDalicPINVOKE.ImageView_New__SWIG_2(url), true) {
      if (NDalicPINVOKE.SWIGPendingException.Pending) throw NDalicPINVOKE.SWIGPendingException.Retrieve();

  }
  public ImageView(ImageView imageView) : this(NDalicPINVOKE.new_ImageView__SWIG_1(ImageView.getCPtr(imageView)), true) {
    if (NDalicPINVOKE.SWIGPendingException.Pending) throw NDalicPINVOKE.SWIGPendingException.Retrieve();
  }



  public void SetImage(string url) {
    NDalicPINVOKE.ImageView_SetImage__SWIG_1(swigCPtr, url);
    if (NDalicPINVOKE.SWIGPendingException.Pending) throw NDalicPINVOKE.SWIGPendingException.Retrieve();
  }


  public Image GetImage() {
    Image ret = new Image(NDalicPINVOKE.ImageView_GetImage(swigCPtr), true);
    if (NDalicPINVOKE.SWIGPendingException.Pending) throw NDalicPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }


  public string ResourceUrl 
  { 
    get 
    {
      string temp;
      GetProperty( ImageView.Property.RESOURCE_URL).Get( out temp );
      return temp;
    }
    set 
    { 
      SetProperty( ImageView.Property.RESOURCE_URL, new Dali.Property.Value( value ) );
    }
  }
  public Dali.Property.Map ImageMap 
  { 
    get 
    {
      Dali.Property.Map temp = new Dali.Property.Map();
      GetProperty( ImageView.Property.IMAGE).Get(  temp );
      return temp;
    }
    set 
    { 
      SetProperty( ImageView.Property.IMAGE, new Dali.Property.Value( value ) );
    }
  }
  public bool PreMultipliedAlpha 
  { 
    get 
    {
      bool temp = false;
      GetProperty( ImageView.Property.PRE_MULTIPLIED_ALPHA).Get( ref temp );
      return temp;
    }
    set 
    { 
      SetProperty( ImageView.Property.PRE_MULTIPLIED_ALPHA, new Dali.Property.Value( value ) );
    }
  }
  public Vector4 PixelArea 
  { 
    get 
    {
      Vector4 temp = new Vector4(0.0f,0.0f,0.0f,0.0f);
      GetProperty( ImageView.Property.PIXEL_AREA).Get(  temp );
      return temp;
    }
    set 
    { 
      SetProperty( ImageView.Property.PIXEL_AREA, new Dali.Property.Value( value ) );
    }
  }

}

}
